### ISSUE TITLE
Migration missing for 1.1.0?

### ISSUE THREAD

**Issue by Leinad4Mind** [andreaskou/PHPBB_IUM#12]
For those who had 1.0.0 and installed this last 1.1.0 when we do login an sql message appears saying unknown table.

**Comment by andreaskou** [comment]
A complete uninstall of IUM needs to be performed prior installation of 1.1.0
Could I have the complete message?
Screenshot perhaps?

Thanks for reporting!

**Comment by Leinad4Mind** [comment]
Thats what I did, I uninstall it since I didnt make use of it yet and then install again and it was all ok.

I would need to install 1.0.0 again to see the error ^^' But basically its a migration problem that doesnt take care of the tables. Probably its not possible to rename tables there.

**Comment by andreaskou** [comment]
Well from previous version to the current one there where some major changes.
Because of phpbb team requested me to use their tables "users" and not to create extra (custom) tables. I had to modify the ext in this manner. So this is not an actual "problem". It suppose to not handle the old custom table. And I have not made any scripts to check if there was a previous version installed, to do the moving of any data in the background in the current version, because it's simply not an official release. It's still has to be accepted by phpbb.
If this release will be accepted and in the future there will be such major changes I will make sure that it will support previous versions.
